---

- name: check if .prlctl_version is created
  ansible.windows.win_stat:
    path: '{{ ansible_user_dir | default("") }}\.prlctl_version'
  register: check_prlctl_version_file
  ignore_errors: true

- name: parallels version
  block:
    - name: get parallels version.
      ansible.builtin.slurp:
        src: '{{ ansible_user_dir }}\.prlctl_version'
      register: get_parallels_version

    - name: set parallels version.
      ansible.builtin.set_fact:
        parallels_version: "{{ get_parallels_version['content'] | b64decode }}"
  when: check_prlctl_version_file.stat.exists

- name: check for mounted iso location
  ansible.windows.win_stat:
    path: '{{ parallels_mounted_iso_drive }}:\PTAgent.exe'
    get_checksum: false
  register: check_mounted_iso_location

- name: iso file
  block:
    - name: check for iso file
      ansible.windows.win_stat:
        path: '{{ parallels_iso_file }}'
        get_checksum: false
      register: check_parallels_iso_file

    - name: download iso file if needed
      ansible.windows.win_get_url:
        url: '{{ parallels_tools_download_url }}'
        dest: '{{ parallels_iso_file }}'
      when: not check_parallels_iso_file.stat.exists

    - name: mount iso
      community.windows.win_disk_image:
        image_path: '{{ parallels_iso_file }}'
        state: present
      register: disk_image_out

    - name: install parallels tools
      ansible.builtin.include_tasks: install.yml
      vars:
        _mounted_drive: "{{ disk_image_out.mount_paths[0] }}"

  always:
    - name: unmount iso
      community.windows.win_disk_image:
        image_path: '{{ parallels_iso_file }}'
        state: absent

    - name: remove iso file
      ansible.windows.win_file:
        path: '{{ parallels_iso_file }}'
        state: absent
  when:
    - not check_mounted_iso_location.stat.exists
    - parallels_tools_download_url | length

- name: install parallels tools
  ansible.builtin.include_tasks: install.yml
  when: check_mounted_iso_location.stat.exists
  vars:
    _mounted_drive: "{{ parallels_mounted_iso_drive }}"
